name: Python CI

on: [push, pull_request]

jobs:
  check_python_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Check Python version
        run: python --version
  pylint:
    runs-on: ubuntu-latest
    needs: check_python_version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pylint
        run: python -m pylint test_app.py
